[build.environment]
  GO_IMPORT_PATH = "github.com/ErshovYS/hackathonLCT2023"
  GO111MODULE = "on"
  DB_DSN="test.db"
  DB_TYPE="sqlite"
  CI="false"

[dev]
  command = "./main"
  port = 3000
  targetPort = 8080
  publish = "public"
